import type { WorkspaceData } from "../types";

export const mockData: WorkspaceData = {
  staff: [
    { id: "staff-1", name: "Rahim Manager", role: "manager", monthly_salary: 35000, salary_due: 12000 },
    { id: "staff-2", name: "Karim Mechanic", role: "mechanic", monthly_salary: 25000, salary_due: 0 },
    { id: "staff-3", name: "Nasir Accountant", role: "accountant", monthly_salary: 30000, salary_due: 8000 },
  ],
  customers: [
    { id: "cust-1", name: "Rahim Uddin", phone: "01711111111", address: "Dinajpur Sadar", nid_number: "1988123456789", status: "Regular" },
    { id: "cust-2", name: "Karim Ahmed", phone: "01822222222", address: "Birampur, Dinajpur", status: "Risky" },
    { id: "cust-3", name: "Salma Akter", phone: "01933333333", address: "Mirpur, Dhaka", status: "Good Payer" },
  ],
  bikes: [
    {
      id: "bike-1",
      brand: "Suzuki",
      model: "Gixxer SF",
      color: "Matte Blue",
      year: 2025,
      chassis_number: "SZKGXSF260001",
      engine_number: "ENGSZK0001",
      purchase_price: 220000,
      supplier_name: "Suzuki Dealer BD",
      purchase_date: "2026-05-01",
      current_status: "Sold",
      location: "Showroom",
    },
    {
      id: "bike-2",
      brand: "Suzuki",
      model: "Access 125",
      color: "Red",
      year: 2025,
      chassis_number: "SZKACS260002",
      engine_number: "ENGSZK0002",
      purchase_price: 145000,
      supplier_name: "Suzuki Dealer BD",
      purchase_date: "2026-05-04",
      current_status: "Sold",
      location: "Showroom",
    },
    {
      id: "bike-3",
      brand: "Suzuki",
      model: "Gixxer",
      color: "Black",
      year: 2026,
      chassis_number: "SZKGIX26003",
      engine_number: "ENGSZK0003",
      purchase_price: 238000,
      supplier_name: "Suzuki Dealer BD",
      purchase_date: "2026-05-14",
      current_status: "Available",
      location: "Showroom",
    },
    {
      id: "bike-4",
      brand: "Suzuki",
      model: "Hayate EP",
      color: "Black",
      year: 2025,
      chassis_number: "SZKHYT260004",
      engine_number: "ENGSZK0004",
      purchase_price: 172000,
      supplier_name: "Suzuki Dealer BD",
      purchase_date: "2026-05-12",
      current_status: "Reserved",
      location: "Warehouse",
    },
  ],
  parts: [
    { id: "part-1", part_name: "Engine Oil 10W-40", category: "Oil", brand: "Castrol", quantity_available: 9, purchase_price_per_unit: 620, selling_price_per_unit: 850, supplier_name: "Parts Hub", minimum_stock_level: 12, location: "Shelf A1" },
    { id: "part-2", part_name: "Brake Pad Set", category: "Brake", brand: "Nissin", quantity_available: 18, purchase_price_per_unit: 500, selling_price_per_unit: 750, supplier_name: "Parts Hub", minimum_stock_level: 10, location: "Shelf B2" },
    { id: "part-3", part_name: "Chain Kit", category: "Chain", brand: "DID", quantity_available: 4, purchase_price_per_unit: 2100, selling_price_per_unit: 2900, supplier_name: "Moto Parts", minimum_stock_level: 5, location: "Shelf C1" },
  ],
  sales: [
    {
      id: "sale-1",
      sale_no: "SALE-2026-0001",
      sale_date: "2026-05-17",
      customer_id: "cust-1",
      customer_name: "Rahim Uddin",
      customer_phone: "01711111111",
      bike_id: "bike-1",
      bike_brand: "Suzuki",
      bike_model: "Gixxer SF",
      bike_color: "Matte Blue",
      chassis_number: "SZKGXSF260001",
      engine_number: "ENGSZK0001",
      purchase_price: 220000,
      selling_price: 250000,
      discount: 5000,
      additional_sale_expense: 2000,
      paid_amount: 170000,
      due_amount: 80000,
      profit: 23000,
      payment_type: "Partial Payment",
      payment_method: "Cash",
      salesperson: "Rahim Manager",
      notes: "Due agreed for June collection.",
    },
    {
      id: "sale-2",
      sale_no: "SALE-2026-0002",
      sale_date: "2026-05-07",
      customer_id: "cust-2",
      customer_name: "Karim Ahmed",
      customer_phone: "01822222222",
      bike_id: "bike-2",
      bike_brand: "Suzuki",
      bike_model: "Access 125",
      bike_color: "Red",
      chassis_number: "SZKACS260002",
      engine_number: "ENGSZK0002",
      purchase_price: 145000,
      selling_price: 173000,
      discount: 3000,
      additional_sale_expense: 1500,
      paid_amount: 138000,
      due_amount: 35000,
      profit: 23500,
      payment_type: "Loan",
      payment_method: "bKash",
      salesperson: "Rahim Manager",
    },
  ],
  dues: [
    {
      id: "due-1",
      sale_id: "sale-1",
      customer_id: "cust-1",
      customer_name: "Rahim Uddin",
      customer_phone: "01711111111",
      bike_details: "Suzuki Gixxer SF / SZKGXSF260001",
      total_selling_price: 250000,
      paid_amount: 170000,
      due_amount: 80000,
      remaining_due: 80000,
      due_date: "2026-06-10",
      installment_type: "One-time",
      installment_amount: 80000,
      payment_status: "Pending",
      payment_method: "Cash",
      guarantor_name: "Md. Jalal",
      guarantor_phone: "01799999999",
    },
    {
      id: "due-2",
      sale_id: "sale-2",
      customer_id: "cust-2",
      customer_name: "Karim Ahmed",
      customer_phone: "01822222222",
      bike_details: "Suzuki Access 125 / SZKACS260002",
      total_selling_price: 173000,
      paid_amount: 138000,
      due_amount: 35000,
      remaining_due: 35000,
      due_date: "2026-05-25",
      installment_type: "Multiple installments",
      installment_amount: 17500,
      payment_status: "Pending",
      payment_method: "bKash",
    },
  ],
  duePayments: [],
  services: [
    { id: "svc-1", service_no: "SVC-2026-0001", service_date: "2026-05-19", customer_id: "cust-3", customer_name: "Salma Akter", customer_phone: "01933333333", bike_brand: "Suzuki", bike_model: "Gixxer", service_type: "Oil change", parts_used: "Engine Oil 10W-40 x1", service_charge: 600, parts_cost: 850, total_bill: 1450, paid_amount: 1450, due_amount: 0, payment_method: "Cash", mechanic_name: "Karim Mechanic" },
    { id: "svc-2", service_no: "SVC-2026-0002", service_date: "2026-05-20", customer_id: "cust-1", customer_name: "Rahim Uddin", customer_phone: "01711111111", bike_brand: "Suzuki", bike_model: "Gixxer SF", service_type: "Brake repair", parts_used: "Brake Pad Set x1", service_charge: 700, parts_cost: 750, total_bill: 1450, paid_amount: 1000, due_amount: 450, payment_method: "Cash", mechanic_name: "Karim Mechanic" },
  ],
  debits: [
    { id: "debit-1", transaction_date: "2026-05-01", category: "Bike purchase", amount: 220000, payment_method: "Bank", person: "Suzuki Dealer BD", purpose: "Gixxer SF stock purchase", related_module: "Bike stock", added_by: "Nasir Accountant" },
    { id: "debit-2", transaction_date: "2026-05-04", category: "Bike purchase", amount: 145000, payment_method: "Bank", person: "Suzuki Dealer BD", purpose: "Access 125 stock purchase", related_module: "Bike stock", added_by: "Nasir Accountant" },
    { id: "debit-3", transaction_date: "2026-05-18", category: "Salary", amount: 45000, payment_method: "Cash", person: "Staff", purpose: "Partial salary payments", related_module: "Salary", added_by: "Nasir Accountant" },
  ],
  credits: [
    { id: "credit-1", transaction_date: "2026-05-17", category: "Bike sale", amount: 170000, payment_method: "Cash", person: "Rahim Uddin", purpose: "SALE-2026-0001 initial payment", related_module: "Bike sale", added_by: "Rahim Manager" },
    { id: "credit-2", transaction_date: "2026-05-07", category: "Bike sale", amount: 138000, payment_method: "bKash", person: "Karim Ahmed", purpose: "SALE-2026-0002 initial payment", related_module: "Bike sale", added_by: "Rahim Manager" },
    { id: "credit-3", transaction_date: "2026-05-19", category: "Service", amount: 1450, payment_method: "Cash", person: "Salma Akter", purpose: "SVC-2026-0001", related_module: "Service", added_by: "Karim Mechanic" },
  ],
  salaryPayments: [
    { id: "salary-1", staff_id: "staff-1", staff_name: "Rahim Manager", salary_month: "2026-05", bonus_amount: 5000, bonus_type: "Sales bonus", payment_date: "2026-05-18", paid_amount: 28000, due_salary: 12000, payment_method: "Cash" },
  ],
  homeExpenses: [
    { id: "home-1", home: "Dhaka", expense_date: "2026-05-03", category: "Rent", amount: 18000, paid_by: "Owner", payment_method: "Bank" },
    { id: "home-2", home: "Dinajpur", expense_date: "2026-05-06", category: "Family support", amount: 12000, paid_by: "Owner", payment_method: "Cash" },
  ],
  others: [
    { id: "other-1", record_date: "2026-05-11", type: "Expense", category: "Document cost", amount: 2500, description: "Registration support documents", payment_method: "Cash", added_by: "Nasir Accountant" },
    { id: "other-2", record_date: "2026-05-13", type: "Income", category: "Owner investment", amount: 50000, description: "Owner cash injection", payment_method: "Bank", added_by: "Owner" },
  ],
  activity: [
    { id: "act-1", actor: "Rahim Manager", action: "Added bike sale SALE-2026-0001", entity: "Bike Sale", created_at: "2026-05-17T10:30:00Z" },
    { id: "act-2", actor: "Karim Mechanic", action: "Completed service SVC-2026-0001", entity: "Service", created_at: "2026-05-19T14:15:00Z" },
    { id: "act-3", actor: "Nasir Accountant", action: "Recorded salary debit", entity: "Debit", created_at: "2026-05-18T09:00:00Z" },
  ],
};
